mysql:
  enabled: true
  url: "jdbc:mysql://sql.bloom.host:3306/yourdatabaselink"
  user: "u68391_your_username"
  password: "your_password"
sync-interval-ticks: 1728000 # 24 hours in ticks 
minimum-playtime-ticks: 72000 # 1 hour
sync-on-join: true
placeholderapi:
  enabled: true
  placeholders: # Enter placeholders without % (e.g., vault_balance, not %vault_balance%)
    - vault_eco_balance
  blacklist: # Enter placeholders to exclude without % (e.g., townyadvanced_townboard)
    - townyadvanced_townboard
    - townyadvanced_nationboard
towny:
  enabled: true
export:
  interval-ticks: 72000
  compression: true
  cleanup:
    enabled: false
    warning: "DO NOT ENABLE UNLESS YOU WANT TO DELETE OLD DATA! MAKE BACKUPS!"
    active_days: 30
    keep_files_days: 90
logging:
  level: verbose