mysql:
  enabled: true
  url: "jdbc:mysql://sql.bloom.host:3306/yourdatabaselink"
  user: "u68391_your_username"
  password: "your_password"
sync-interval-ticks: 1728000 # 24 hours in ticks 
minimum-playtime-ticks: 72000 # 1 hour
sync-on-join: true
placeholderapi:
  enabled: true
  placeholders: # Enter placeholders without % (e.g., vault_balance, not %vault_balance%)
    - vault_balance
    - player_kills
    - essentials_lastlogin
    - essentials_firstlogin
  blacklist: # Enter placeholders to exclude without % (e.g., townyadvanced_townboard)
    - townyadvanced_townboard
    - townyadvanced_nationboard
towny:
  enabled: true
export:
  interval-ticks: 72000
  compression: true
  cleanup:
    enabled: false
    warning: "DO NOT ENABLE UNLESS YOU WANT TO DELETE OLD DATA! MAKE BACKUPS!"
    active_days: 30
    keep_files_days: 90
simplify-stat-names: true
stat-display-names:
  sprint_one_cm: "Sprint Distance"
  stone: "Stone Mined"
  dirt: "Dirt Mined"
  zombie: "Zombies Killed"
  mutton: "Mutton Used"
  vault_balance: "Balance"
  essentials_lastlogin: "Last Login"
  essentials_firstlogin: "First Joined"
logging:
  level: verbose